config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "blog_posts#index"

  resources :blog_posts, except: [:destroy] do
    resources :comments, only: [:create]
  end

  # Log in form
  resources :sessions, only: [:new, :create] # we dont care about showing a session
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog_post.rb
class BlogPost < ApplicationRecord
  has_many :comments

  validates :title, presence: true
  validates :body, presence: true, length: { minimum: 10 }
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :blog_post

  validates :user, :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord

  # let's call a method that adds a bunch of functionality to making sure this is a secure password
  has_secure_password

  validates :name, :email,  presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  # this is a way to access these ApplicationController methods in the view files
  # Only just for applicationControllers

  helper_method :current_user
  helper_method :logged_in?

  def current_user
    return nil if session[:user_id].blank?
    # User.find(session[:user_id])
    # memoization data - makes saving this user info more efficient:
    @current_user ||= User.find(session[:user_id])
  end

  def logged_in?
    # session[:user_id].present?
    # or you can do this:

    current_user.present?
  end
end

app/controllers/blog_posts_controller.rb
class BlogPostsController < ApplicationController
  def index
    @blog_posts = BlogPost.all
  end

  def show
    # raise = throw an error
    # inspect = shows a string representation of that item
    # "hey".inspect
    # raise params.inspect
    @blog_post = BlogPost.find(params[:id])
    @comment = @blog_post.comments.new
  end

  private

  def blog_post_params
    params.require(:blog_post).permit(:title, :body)
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  # before_action :load_blog_posts

  def create
    @blog_post = BlogPost.find(params[:blog_post_id])
    @comment = @blog_post.comments.new(comment_params)

    if @comment.save
      # flash[:success] = "You added a comment!"
      redirect_to blog_post_url(@blog_post)
    else
      # flash[:error] = "You have issues"
      render "blog_posts/show"
    end
  end


  private

  # def load_blog_posts
  #   @blog_post = BlogPost.find(params[:blog_post_id])
  # end

  def comment_params
    params.require(:comment).permit(:user, :body)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :verify_authenticity_token


  def create
    user = User.find_by(email: params[:email])

    if user && user.authenticate(params[:password])
      session[:user_id] = user.id # set the session user id to be the user.id |  this is encrypted
      redirect_to root_url # like calling two methods redirect_to(root_url())
    else
      render :new   # render(:new)
    end
  end
end



# user same as user.present?

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_posts_helper.rb
module BlogPostsHelper
end

app/views/blog_posts/index.html.erb
<h1>Blog Posts</h1>
<ul>
  <% @blog_posts.each do |post| %>
    <li>
      <%= link_to(post.title, blog_post_path(post)) %>
    </li>
  <% end %>
</ul>

app/views/blog_posts/show.html.erb
<h2><%= @blog_post.title %></h2>
<p><%= @blog_post.body %></p>

<h3>Blog Comments</h3>

<%= form_with(model: @comment, url: [@blog_post, @comment]) do |f| %>
  <% if @comment.errors.any? %>
    <p><%= @comment.errors.map(&:full_message).join(", ") %></p>
  <% end %>


  <div>
    <%= f.label :user %>
    <%= f.text_field :user %>
  </div>

  <div>
    <%= f.label :body %>
    <%= f.text_field :body %>
  </div>

  <%= f.submit "Submit comment" %>
<% end %>

<ul>
  <% @blog_post.comments.order(created_at: :desc).each do |comment| %>
    <li>
      <p><%= comment.body %></p>
      <p>From user: <strong><%= comment.user %></strong></p>
    </li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav>
      <% if logged_in? %>
        <%= current_user.name %>
      <% else %>
        <%= link_to(new_session_url, "Log In") %>
      <% end %>
    </nav>

    <%= yield %>
  </body>
</html>